In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1 D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
type(arr1)

# this very similar to list in python
list1 = [1, 2, 3, 4, 5]
print("List:", list1)
type(list1)


# only difference is that how they store data in memory

1D Array: [1 2 3 4 5]
List: [1, 2, 3, 4, 5]


list

In [4]:
mix_value = [1, 2.5, 'hello', True]
type(mix_value)

# but you can control the data type in numpy array
arr2 = np.array([1, 2, 3, 4, 5,'hello'], dtype='U10')
print("Array with specified data type:", arr2)
type(arr2)

Array with specified data type: ['1' '2' '3' '4' '5' 'hello']


numpy.ndarray

In [5]:
# lets say yoi have 2 d data
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr3)
print("Shape of 2D Array:", arr3.shape)


# I want to do scalar multiplication,addition on array
arr4 = arr3 * 2
print("Array after multiplication:\n", arr4)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D Array: (2, 3)
Array after multiplication:
 [[ 2  4  6]
 [ 8 10 12]]


In [6]:
# I willl try the same with list
list2 = [[1, 2, 3], [4, 5, 6]]
# list2 +2  # this will give error
list2+2

TypeError: can only concatenate list (not "int") to list

In [8]:
# some time we geenrate fake data for testing purpose
# numpy has inbuilt function to generate random data
rand_arr = np.random.rand(3,4)  # 3 rows and 4
print("Random Array:\n", rand_arr)

Random Array:
 [[0.18414085 0.25221102 0.27343892 0.80128311]
 [0.88430976 0.2097464  0.36112641 0.4419135 ]
 [0.83643228 0.9567373  0.25477112 0.0016781 ]]


In [9]:
age = np.random.randint(18, 60, size=50)
print("Random Age Array:\n", age)

Random Age Array:
 [39 18 34 30 30 52 20 58 36 27 27 51 22 53 18 32 45 58 31 46 22 25 59 59
 33 58 51 52 32 59 29 26 29 18 49 46 23 45 44 43 18 25 18 50 33 19 56 34
 39 37]


In [10]:
product_cat = ['Electronics', 'Clothing', 'Home', 'Books', 'Toys']
rand_cat = np.random.choice(product_cat, size=50)
print("Random Product Categories:\n", rand_cat)

Random Product Categories:
 ['Electronics' 'Home' 'Books' 'Clothing' 'Home' 'Electronics'
 'Electronics' 'Electronics' 'Electronics' 'Home' 'Home' 'Toys' 'Home'
 'Home' 'Toys' 'Toys' 'Books' 'Toys' 'Clothing' 'Clothing' 'Toys' 'Toys'
 'Books' 'Clothing' 'Electronics' 'Clothing' 'Books' 'Clothing' 'Home'
 'Books' 'Toys' 'Electronics' 'Electronics' 'Books' 'Home' 'Electronics'
 'Toys' 'Toys' 'Clothing' 'Clothing' 'Books' 'Books' 'Books' 'Electronics'
 'Home' 'Books' 'Books' 'Home' 'Home' 'Clothing']


In [11]:
data = pd.DataFrame({
    'Age': age,
    'Product_Category': rand_cat
})

data.head()

,Age,Product_Category
0,39,Electronics
1,18,Home
2,34,Books
3,30,Clothing
4,30,Home


In [12]:
np.mean(age)
np.median(age)
np.std(age)

np.float64(13.390085884713361)

In [13]:
# compare array with list for performance
import time
import numpy as np

# create a large list and array
size = 100000000
list_data = list(range(size))
array_data = np.arange(size)

# measure time for list
start = time.time()
list_result = [x * 2 for x in list_data]
print("List processing time:", time.time() - start)

# measure time for array
start = time.time()
array_result = array_data * 2
print("Array processing time:", time.time() - start)


List processing time: 3.3390257358551025
Array processing time: 0.39064502716064453


In [14]:
# memory usage
import sys

# create a large list and array
size = 1000
list_data = list(range(size))
array_data = np.arange(size)

# measure memory usage for list
print("List memory usage:", sys.getsizeof(list_data))
# in kb
print("List memory usage (KB):", sys.getsizeof(list_data)/1024)

# measure memory usage for array
print("Array memory usage:", array_data.nbytes)
# in kb
print("Array memory usage (KB):", array_data.nbytes/1024)


List memory usage: 8056
List memory usage (KB): 7.8671875
Array memory usage: 8000
Array memory usage (KB): 7.8125


In [6]:
# random selection time comparison
import time
import numpy as np
size = 1000
list_data = list(range(size))
array_data = np.arange(size)
# measure time for random selection in list
start = time.time()
for _ in range(1000):
    _ = np.random.choice(list_data)
print("List random selection time:", time.time() - start)

# measure time for random selection in array
start = time.time()
for _ in range(1000):
    _ = np.random.choice(array_data)
print("Array random selection time:", time.time() - start)

List random selection time: 0.05043792724609375
Array random selection time: 0.0035238265991210938


In [ ]:
# Conclusion: Numpy arrays are more efficient in terms of memory and performance for numerical computations compared to Python lists.
# Additionally, Numpy provides a wide range of mathematical functions and operations that are optimized for performance.


In [15]:
# lets prepare customer data
rand_arr = np.random.rand(3,4)  # 3 rows and 4 columns
print("Random Array:\n", rand_arr)

Random Array:
 [[0.90005679 0.24973315 0.27450085 0.97778866]
 [0.08394797 0.28695944 0.93707214 0.21477043]
 [0.34829348 0.61329472 0.31489136 0.46086903]]
