# Day 12 Assignments: NumPy + Pandas

Complete each task and replace the TODOs. Each task includes `assert` checks to verify your result.


## NumPy Task: Stack and summarize
You are given two arrays of scores.

1) Stack them into a 2D array (rows)
2) Compute the mean of each column
3) Compute the overall standard deviation


In [7]:
import numpy as np

a = np.array([70.0, 80.0, 90.0])
b = np.array([60.0, 85.0, 95.0])

# TODO: stack into 2D array
stacked = np.stack((a, b), axis=0)
print(stacked)

# TODO: compute column means
col_means = np.mean(stacked, axis=0)
print(col_means)

# TODO: compute overall std
overall_std = np.std(stacked)
print(overall_std)

expected_stacked = np.vstack([a, b])
expected_means = expected_stacked.mean(axis=0)
expected_std = expected_stacked.std()

assert stacked is not None, "stacked is None."
assert col_means is not None, "col_means is None."
assert overall_std is not None, "overall_std is None."
assert np.array_equal(stacked, expected_stacked), f"Expected {expected_stacked}, got {stacked}"
assert np.allclose(col_means, expected_means), f"Expected {expected_means}, got {col_means}"
assert abs(overall_std - expected_std) < 1e-12, f"Expected {expected_std}, got {overall_std}"


[[70. 80. 90.]
 [60. 85. 95.]]
[65.  82.5 92.5]
11.902380714238083


## Pandas Task: Multi-step aggregation
You are given campaign data.

1) Compute click-through rate per row: `clicks / impressions`
2) Compute average CTR per channel sorted descending


In [ ]:
import pandas as pd

campaigns = pd.DataFrame({
    "channel": ["Email", "Search", "Email", "Social", "Search"],
    "clicks": [50, 120, 30, 80, 100],
    "impressions": [1000, 2000, 1200, 1600, 2500],
})
print(campaigns)

# TODO: compute CTR per row
campaigns_clean = campaigns.copy()
campaigns_clean["ctr"] = campaigns_clean["clicks"] / campaigns_clean["impressions"]
print(campaigns_clean)

# TODO: compute average CTR per channel
ctr_by_channel = campaigns_clean.groupby('channel')['ctr'].mean().sort_values(ascending=False)

expected = (campaigns.assign(ctr=campaigns["clicks"] / campaigns["impressions"])
            .groupby("channel")["ctr"].mean()
            .sort_values(ascending=False))

assert ctr_by_channel is not None, "ctr_by_channel is None."
assert ctr_by_channel.equals(expected), f"Expected {expected}, got {ctr_by_channel}"


  channel  clicks  impressions
0   Email      50         1000
1  Search     120         2000
2   Email      30         1200
3  Social      80         1600
4  Search     100         2500
  channel  clicks  impressions    ctr
0   Email      50         1000  0.050
1  Search     120         2000  0.060
2   Email      30         1200  0.025
3  Social      80         1600  0.050
4  Search     100         2500  0.040


AssertionError: ctr_by_channel is None.